### ISSUE TITLE
Increase/decrease step

### ISSUE THREAD

**Issue by marima84** [AnthonMS/ha-slider-card#1]
Hi,
I've just implemented your slider in my configuration.
I'm using it linked with some input.number but even though the step in my input are 0,2 the slider is increasing or decreasing of 1.0. Am I missing something configuration or is not possible to replicate the same increase/decrease step set in the input.number?
If that is the case would it be possible to implemented?

Thank you
Mark

**Comment by AnthonMS** [comment]
You are right, I have not implemented that. It is only possible to step 1 at the moment. I didn't think of this, when I made it. 

It will be possible to implement, and I will try to do it today.

**Comment by AnthonMS** [comment]
It now support custom steps for both lights and input_number.
If you do not specify step in config, it will use step from input_number.attributes.step. If it's a light, it will default to 1.
Hope this helped.

Glad to hear someone is using this, other than me 😃

**Comment by AnthonMS** [comment]
I will close this issue, if it doesn't work, please let me know. But it should work, I tested it on my setup.
