### ISSUE TITLE
bug: strange behavior in browser_mod popup view

### ISSUE THREAD

**Issue by Garulf** [AnthonMS/ha-slider-card#16]
I've racked my brain on this bug. It ONLY appears on iOS in a popup view, and ONLY if the view is scrollable.

Have any idea what would cause this issue?

![IMG_4148](https://user-images.githubusercontent.com/535299/125701025-1229d375-6d57-4881-ae51-5394072f42ff.PNG)

**Comment by Garulf** [comment]
Okay, fixed by adding `overflow: hidden;` to :
```
      .slider-container input[type="range"]::-webkit-slider-runnable-track {
          height: var(--slider-height);
          -webkit-appearance: none;
          color: var(--slider-main-color);
          transition: box-shadow 0.2s ease-in-out;
      }
```
Not sure if this breaks anything yet....

EDIT: Breaks A LOT apparently...

**Comment by AnthonMS** [comment]
Hehe then it was good I didn't just merge it right away. I haven't stumpled upon that bug before, but I don't have any iOS devices either. And I am using it in popups that's scrollable. So it must be an iOS thing. Not sure how to approach a fix for this though.

**Comment by Garulf** [comment]
This seems to fix it:
```
      .slider-container {
          height: var(--container-height);
          position: relative;
          overflow: hidden;
          border-radius: var(--slider-radius);
      }
```

Doesn't seem to break anything yet.....

**Comment by AnthonMS** [comment]
Okay let me know when you're ready for it to be merged, and I will do it. I'm a little short on time at the moment, so don't really have time to sit down and test the changes you make, so I just assume you are testing it :)

**Comment by Garulf** [comment]
Yeah, I want to test this one a little further before i call it 100% fixed. I'll let you know once I'm done.

**Comment by Garulf** [comment]
Tested on iOS, Chrome, Firefox ([Still has its own issues](https://github.com/AnthonMS/ha-slider-card/issues/5)).

No issues are added from this change.

**Comment by AnthonMS** [comment]
Okay, yeah I don't know why it looks like that on Firefox, probably just me not grabbing the right css properties for all browsers.

**Comment by Garulf** [comment]
Just found a fix for that (firefox issue), I'll submit a PR once I finish testing

**Comment by AnthonMS** [comment]
Amazing! Thanks!

**Comment by Garulf** [comment]
No problem! I ran into the fix while fixing my own issue so why not, right?

**Comment by Garulf** [comment]
After testing there seems to be no issues with this fix.

https://github.com/AnthonMS/ha-slider-card/pull/19

**Comment by AnthonMS** [comment]
That's good, I have merged the fix. Hopefully it doesn't come up again :)
