### ISSUE TITLE
Incorporate into HACS

### ISSUE THREAD

**Issue by bluesheep** [AnthonMS/ha-slider-card#2]
I've been looking for a card like this, but I'm loathed to do manual file management. It would be great if it could be included in HACS!

Richard

**Comment by AnthonMS** [comment]
I wouldn't mind getting it working with HACS. But I haven't been able to find any documentation on how I manage that. So send me a link on how I do it, and I will do it as soon as I have time

**Comment by bluesheep** [comment]
(edited for clarity)
It took me a while to find it, but the HACS documentation on this seems pretty comprehensive (to my untrained eye). I've linked to it [here](https://hacs.xyz/docs/publish/start)

**Comment by AnthonMS** [comment]
Thanks. Yes it does seem comprehensive and exactly what I have been looking for. So I will take a look throughout the weekend.

**Comment by AnthonMS** [comment]
If you add this repository as a custom repo in HACS, you will now be able to install it through that.

**Comment by bluesheep** [comment]
Looks great, thanks! I’ll play around tomorrow
