### ISSUE TITLE
Slider doesn't change value on input number

### ISSUE THREAD

**Issue by perern** [AnthonMS/ha-slider-card#23]
`type: custom:slider-card

entity: input_number.task_timer`

When I press on the bar or drag it the input number doesn't change. But the slider changes when I change the input number manually.

**Comment by AnthonMS** [comment]
Sounds like I'm calling the wrong home assistant function when using input_slider, I don't know when this error happened since it worked at some point.

I will take a look at whats going on, during the next couple of days.

**Comment by AnthonMS** [comment]
This repo has been archived, becuase of some major changes breaking peoples setups. 

Read the readme to find new repo link. You are more than welcome to make this issue on the new repo.

**Comment by perern** [comment]
> This repo has been archived, becuase of some major changes breaking peoples setups.
> 
> Read the readme to find new repo link. You are more than welcome to make this issue on the new repo.

The new one worked. :)

**Comment by AnthonMS** [comment]
Perfect! :)
