### ISSUE TITLE
Initial state on fan domain is always 50%

### ISSUE THREAD

**Issue by Garulf** [AnthonMS/ha-slider-card#4]
On initial load slider indicates 50% speed on fan entity.

**Comment by AnthonMS** [comment]
I don't have any fans to test it with, so have made it from the fan entity documentation. So it hasn't been tested at all from my side of things, and I can't really test it in my setup. Sorry about that.

Would it be possible to just make an input_slider and an automation that sets the fan speed to what the state of the input_slider is when it's changed? It should be pretty easy to get around that bug that way.


If it's really important to you, we will have to figure something out so I can test it somehow. I tried making a dummy fan entity, but I couldn't get it to work properly.

**Comment by AnthonMS** [comment]
And I remember I had a similar problem with the media_player, and it took a lot of testing to get it to work how it's supposed to.

**Comment by Garulf** [comment]
Finally got around to debugging this issue i was having. I think it was a typo.

Please check your pull requests.

**Comment by AnthonMS** [comment]
It has been approved and merged. 

Thanks!
